src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpruntRepository::class)
 */
class Emprunt
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $book_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateEmprunt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dateRendu;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getBookId(): ?int
    {
        return $this->book_id;
    }

    public function setBookId(int $book_id): self
    {
        $this->book_id = $book_id;

        return $this;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->dateEmprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $dateEmprunt): self
    {
        $this->dateEmprunt = $dateEmprunt;

        return $this;
    }

    public function getDateRendu(): ?string
    {
        return $this->dateRendu;
    }

    public function setDateRendu(string $dateRendu): self
    {
        $this->dateRendu = $dateRendu;

        return $this;
    }
}

src/Form/EmpruntType.php
<?php

namespace App\Form;

use App\Entity\Emprunt;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType as TypeTextType;

class EmpruntType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user_id')
            ->add('book_id')
            ->add('dateEmprunt')
            ->add('dateRendu', TypeTextType::class, [
                'empty_data' => '-1'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Emprunt::class,
        ]);
    }
}

src/Controller/EmpruntController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\BookRepository;
use App\Repository\EmpruntRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EmpruntController extends AbstractController
{

    /**
    * @Route("/compte/emprunt", name="emprunt_user", methods={"GET"})
    */
    public function getEmprunt(EmpruntRepository $empruntRepo, BookRepository $bookRepo){
        $user = $this->getUser(); //recupere user connecté
        //$idUser= htmlspecialchars($req->get('user_id'));
        //  to get the id of the user, instead if session with request we user user entity direct and it recognises the id of the user
        // and then the follwing code can be used to link with the books borrowed. 
        $getEmprunt = $empruntRepo->findAll(['user_id' => $user->getId()]);
        //  start with a variable table is empty and do loop to display all books whichver borrowed
        // get emprunt has all the user id of table emprunt which has all the information
        // and the loop starts with a table consisting of all the elements needed to display now go to view and start it.
        $emprunts = [];

        foreach($getEmprunt as $emprunt){
            $emprunts[$emprunt->getId()] = [
                'user_id' => $emprunt->getUserId(),
                'date_emprunt' => $emprunt->getDateEmprunt(),
                'date_rendu' => $emprunt->getDateRendu(),
                'book' => $bookRepo->findOneBy(['id' => $emprunt->getBookId()])
            ];
        }
        // we needed bookRepo to find the id for the book and display in loop. data can be table with key and value or just a variable
        // return $this->json(['emprunts' => $emprunts], 200, [], ['groups'=>'book_get']);
        return $this->render("emprunt/index.html.twig",[
            "emprunts" => $emprunts
        ]);
    }
}

src/Controller/EmpruntsController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Emprunt;
use App\Form\EmpruntType;
use App\Form\EmpruntEmailType;
use App\Repository\EmpruntRepository;
use App\Repository\BookRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmpruntsController extends AbstractController
{

    /**
     * @Route("/admin/emprunts/new", name="emprunts_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $emprunt = new Emprunt();
        $form = $this->createForm(EmpruntType::class, $emprunt);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($emprunt);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('emprunts/new.html.twig', [
            'emprunt' => $emprunt,
            'form' => $form->createView(),
        ]);
    }

    
    /**
     * @Route("/admin/emprunts/list/{id}", name="emprunts_listuser", methods={"GET","POST"})
     */
    public function showForAUser(User $user, EmpruntRepository $repoEmprunts, BookRepository $bookRepo): Response
    {
        $result = $repoEmprunts->findBy(['user_id' => $user->getId()]);

        $emprunts = [];

        foreach($result as $emprunt){
            $emprunts[$emprunt->getId()] = [
                'id' => $emprunt->getId(),
                'user_id' => $emprunt->getUserId(),
                'date_emprunt' => $emprunt->getDateEmprunt(),
                'date_rendu' => $emprunt->getDateRendu(),
                'book' => $bookRepo->findOneBy(['id' => $emprunt->getBookId()])
            ];
        }

        return $this->render('emprunts/list.html.twig', [
            'emprunts' => $emprunts,
            'username' => $user->getFullname()
        ]);

    }


    /**
     * @Route("/admin/emprunts/list/{id}/{emprunt_id}/returnBook", name="emprunts_returnBook", methods={"GET","POST"})
     */
    public function returnBook(User $user, String $emprunt_id, EmpruntRepository $repoEmprunts){
        
        $emprunt_id = htmlspecialchars($emprunt_id);
        $emprunt = $repoEmprunts->findOneBy(['id' => $emprunt_id]);

        $date = new \Datetime();
        $date = $date->format('d/m/Y \à H:i');

        $emprunt->setDateRendu($date);

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('emprunts_listuser', ['id' => $user->getId()]);

    }
}

templates/emprunts/_delete_form.html.twig
<form method="post" action="{{ path('emprunts_delete', {'id': emprunt.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ emprunt.id) }}">
    <button class="btn">Delete</button>
</form>

templates/emprunts/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/emprunts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Emprunt{% endblock %}

{% block body %}
    <h1>Edit Emprunt</h1>

    {{ include('emprunts/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('emprunts_index') }}">back to list</a>

    {{ include('emprunts/_delete_form.html.twig') }}
{% endblock %}

templates/emprunts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunt index{% endblock %}

{% block body %}
    <h1>Emprunt index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User_id</th>
                <th>Book_id</th>
                <th>DateEmprunt</th>
                <th>DateRendu</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for emprunt in emprunts %}
            <tr>
                <td>{{ emprunt.id }}</td>
                <td>{{ emprunt.userId }}</td>
                <td>{{ emprunt.bookId }}</td>
                <td>{{ emprunt.dateEmprunt ? emprunt.dateEmprunt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ emprunt.dateRendu }}</td>
                <td>
                    <a href="{{ path('emprunts_show', {'id': emprunt.id}) }}">show</a>
                    <a href="{{ path('emprunts_edit', {'id': emprunt.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('emprunts_new') }}">Create new</a>
{% endblock %}

templates/emprunts/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}AlphaBooks - Liste des Emprunts{% endblock %}

{% block body %}
	<style>
		footer{
			position: absolute;
			bottom: 0;
			left: 0;
			width: 100%;

			z-index: 2;
			padding: 3rem 1.5rem 4rem !important;
		}
	</style>

	<h1 style="text-align: center;" class="title mt-6 mb-2">Listes des Emprunts</h1>
	<p style="text-align: center;" class="mb-6">Emprunts pour <strong>{{ username }}</strong></p>
	<div class="table-container">
		<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth" style=" width: 90%; margin-left: auto; margin-right: auto;">
			<thead>
				<tr>
					<th class="has-text-white-ter has-background-dark">
						ID Emprunt
					</th>
					<th class="has-text-white-ter has-background-dark">
						ID Utilisateur
					</th>
					<th class="has-text-white-ter has-background-dark">
						Titre Livre
					</th>
					<th class="has-text-white-ter has-background-dark">
						Auteur Livre
					</th>
					<th colspan="2" class="has-text-white-ter has-background-dark">
						Date Emrunté
					</th>
					<th class="has-text-white-ter has-background-dark">
						Date Rendu
					</th>
					<th class="has-text-white-ter has-background-danger">
						Rendre le livre
					</th>
				</tr>
			</thead>
			<tbody>
				{% for emprunt in emprunts %}
					<tr>

						<td class="has-text-grey-lighter has-background-primary-dark">
							{{ emprunt.id}}
						</td>
						<td class="has-text-grey-lighter has-background-primary-dark">
							{{ emprunt.user_id}}
						</td>
						<td class="has-text-white has-background-info-dark ">
							{{ emprunt.book.titre}}
						</td>
						<td class="has-text-white has-background-info-dark ">
							{{ emprunt.book.auteur}}
						</td>
						<td class="has-text-white has-background-info-dark " colspan="2">
							{{ emprunt.date_emprunt | date('d/m/Y à H:i')}}
						</td>
						<td class="has-text-white has-background-info-dark ">
							{{ emprunt.date_rendu}}
						</td>
						<td class="has-text-white has-background-info-dark ">
							{% if (emprunt.date_rendu == '') or (emprunt.date_rendu == '-1') %}
								<a class="button is-danger" href="{{ path('emprunts_returnBook', {'id': emprunt.user_id, 'emprunt_id': emprunt.id}) }}">Rendre Livre</a>
							{% endif %}
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="11">Aucun livre</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/emprunts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Emprunt
{% endblock %}

{% block body %}
	<style>
		body{
			position: relative;
			height: 100vh;
		}
		footer{
			position: absolute;
			bottom: 0;
			left: 0;
			width: 100%;

			z-index: 2;
			padding: 3rem 1.5rem 4rem !important;
		}
	</style>

	<h1>Create new Emprunt</h1>

	{{ include('emprunts/_form.html.twig') }}


	<script>
        const inputDateRendu = document.querySelector('#emprunt_dateRendu');
        inputDateRendu.value = '-1';
        inputDateRendu.disabled = 'disabled';
	</script>
{% endblock %}

templates/emprunts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Emprunt{% endblock %}

{% block body %}
    <h1>Emprunt</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ emprunt.id }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ emprunt.userId }}</td>
            </tr>
            <tr>
                <th>Book_id</th>
                <td>{{ emprunt.bookId }}</td>
            </tr>
            <tr>
                <th>DateEmprunt</th>
                <td>{{ emprunt.dateEmprunt ? emprunt.dateEmprunt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DateRendu</th>
                <td>{{ emprunt.dateRendu }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('emprunts_index') }}">back to list</a>

    <a href="{{ path('emprunts_edit', {'id': emprunt.id}) }}">edit</a>

    {{ include('emprunts/_delete_form.html.twig') }}
{% endblock %}